"""empty message

Revision ID: 12c1db213a78
Revises: 13027de93606
Create Date: 2017-05-18 00:46:39.026539

"""

# revision identifiers, used by Alembic.
revision = '12c1db213a78'
down_revision = '13027de93606'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activ',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activ')
    # ### end Alembic commands ###
