"""empty message

Revision ID: 13027de93606
Revises: 7db1fdc48369
Create Date: 2017-05-17 23:48:11.345875

"""

# revision identifiers, used by Alembic.
revision = '13027de93606'
down_revision = '7db1fdc48369'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fall_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fall_event')
    # ### end Alembic commands ###
