"""empty message

Revision ID: 4e9595d48fea
Revises: d601a45365d4
Create Date: 2017-05-14 13:55:16.526293

"""

# revision identifiers, used by Alembic.
revision = '4e9595d48fea'
down_revision = 'd601a45365d4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Text(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('sent', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('env',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_type', sa.Text(), nullable=True),
    sa.Column('x', sa.Text(), nullable=True),
    sa.Column('y', sa.Text(), nullable=True),
    sa.Column('z', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.BigInteger(), nullable=True),
    sa.Column('group', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imu_key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('secret_key', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imu_key')
    op.drop_table('env')
    op.drop_table('hr')
    # ### end Alembic commands ###
