"""empty message

Revision ID: d601a45365d4
Revises: None
Create Date: 2017-05-13 22:59:51.163790

"""

# revision identifiers, used by Alembic.
revision = 'd601a45365d4'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
